print("#############################")
print("#                           #")
print("#Gt. Qowita Celia Aurellizha#")
print("#        2510817120019      #")
print("#                           #")
print("#############################")